### ISSUE TITLE
Delete every theme that is not being used

### ISSUE THREAD

**Issue by brashrebel** [realbig/rbw-functionality#2]
There's a ton of extra themes on this network and we don't need them. They only add to our liability from a security perspective. This must be done carefully though. I'd make yourself a master list of every site on the network (including archived sites) and make note of the parent/child themes they are using. Purge everything else minus the most recent couple WP default themes.

**Comment by d4mation** [comment]
**134** themes have been deleted from the server. :tada:

I added a `mu-plugin` to help determine which themes were not in use. 66 themes are in use on the server (including parent and child themes).

I added `twentysixteen` and `twentyfifteen` to make a grand total of 68 themes on the server. `twentytwelve` is also on the server but that's because it is a parent theme on one of the sites.

![image](https://cloud.githubusercontent.com/assets/7770631/13286265/340550e0-dace-11e5-883e-41b4ec72c264.png)

**Comment by joelworsham** [comment]
:tada: :balloon: :birthday:
