### ISSUE TITLE
Replace ultimate branding

### ISSUE THREAD

**Issue by brashrebel** [realbig/rbw-functionality#3]
There is a network activated plugin that is used for some admin styling and other little things. I think we'd be better off just coding those changes ourselves in this plugin and deleting that one. Right now it does 4 things:
1. Admin bar - replicate but use our actual current logo
2. Site Generator - don't bother replicating
3. Help Content - don't bother replicating (some day we'll make something much better)
4. Email From - not sure what happens without this so figure that out and then we'll decide

**Comment by d4mation** [comment]
For the Admin Bar, are you wanting a similar level of customization? 

Adding a new entry up there with sub-navigation should be fairly simple, but allowing it to be changed without editing the plugin itself would be more complicated. I figure these probably don't change very often, if at all.

![image](https://cloud.githubusercontent.com/assets/7770631/13321058/d34fad2c-db9a-11e5-93e7-5a75862f937d.png)

**Comment by brashrebel** [comment]
We don't need an admin UI for this. Just make it super simple. Don't even make any dropdowns for now. Just make the top item be our logo and link to our main site.

**Comment by d4mation** [comment]
Did a lot of refactoring to the plugin to make it easier to maintain going forward. I'd still like to make it into a Class structure, but that can be done a bit later.

It now has its own folder in `mu-plugins` and is loaded via a file named `load_rbm-functionality.php`. I can include that in GitHub if you'd like, but it is literally just this:

`require WPMU_PLUGIN_DIR . '/rbw-functionality/rbw-functionality.php';`

I wanted to put it into a folder so all the CSS and such that I'm including could be more easily handled in the context of the `mu-plugins` folder as a whole.

I still have Ultimate Branding active so I can investigate the "Email From" option. However, I've disabled its Admin Bar functions and replaced it with this plugin.

**Comment by d4mation** [comment]
It seems that the "Email From" option just allows us to specify globally for the entire site who e-mails sent by the site seem to be from instead of using the WordPress defaults. So in our case, it says "Real Big Websites" with the e-mail address `welcome@realbigwebsites.com`.

However, looking at [this forum post](https://premium.wpmudev.org/forums/topic/two-problems-with-ultimate-branding-and-pro-sites), it doesn't seem to play nicely with Multisite. In fact, it could have been part of the Issue at brashrebel/wordcrash-functionality#5 where before they were made into their own install, their e-mails were showing unexpected Header information.

Would we want to re-implement this, but try to ensure it stays localized to `realbigwebsites.com` so it doesn't affect any other sites?

**Comment by d4mation** [comment]
Deactivated Ultimate Branding.
